"""Add last_scraped_at to manufacturers

Revision ID: 2977e5abb8e8
Revises: 001
Create Date: 2026-09-08 19:12:28.599642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2977e5abb8e8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('last_scraped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturers', 'last_scraped_at')
    # ### end Alembic commands ###
