"""Add scrape_runs

One row per manufacturer scrape, so a gap in the firmware history can be explained.
Without it, a version's first-seen date cannot distinguish "the vendor published
nothing for eight months" from "our scraper was quietly broken for eight months".

Written by hand rather than autogenerated. `init_db` calls `Base.metadata.create_all`
on the healthy path, so the development database already had the table and
autogenerate compared the model against it and emitted an empty migration. A fresh
deployment would then have got the table from create_all and never from a migration,
which is the same app/alembic divergence that made the container migrate the wrong
database file.

Revision ID: 81b8abce3858
Revises: 2977e5abb8e8
Create Date: 2026-09-12 13:20:55.100546
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '81b8abce3858'
down_revision: Union[str, None] = '2977e5abb8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scraper_type", sa.String(length=100), nullable=False),
        sa.Column("manufacturer_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("devices_total", sa.Integer(), nullable=True),
        sa.Column("devices_failed", sa.Integer(), nullable=True),
        sa.Column("devices_without_firmware", sa.Integer(), nullable=True),
        sa.Column("devices_not_checked", sa.Integer(), nullable=True),
        sa.Column("new_versions", sa.Integer(), nullable=True),
        sa.Column("notifications_created", sa.Integer(), nullable=True),
        sa.Column("identical_page_groups", sa.Integer(), nullable=True),
        sa.Column("failed_devices", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["manufacturer_id"], ["manufacturers.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scrape_runs_id"), "scrape_runs", ["id"])
    # Both indexed because the questions this table answers are "what happened to
    # this scraper" and "what happened around this date".
    op.create_index(op.f("ix_scrape_runs_scraper_type"), "scrape_runs", ["scraper_type"])
    op.create_index(op.f("ix_scrape_runs_started_at"), "scrape_runs", ["started_at"])


def downgrade() -> None:
    op.drop_index(op.f("ix_scrape_runs_started_at"), table_name="scrape_runs")
    op.drop_index(op.f("ix_scrape_runs_scraper_type"), table_name="scrape_runs")
    op.drop_index(op.f("ix_scrape_runs_id"), table_name="scrape_runs")
    op.drop_table("scrape_runs")
