"""Add device_models.firmware_availability

Records why a product reports no firmware version, where a scraper has established
why. Without it, three unrelated situations render identically as "Firmware Unknown":
a vendor that publishes nothing, a product that takes no firmware at all, and a
scraper that has quietly broken.

Nullable with no default, and NULL is the common case rather than a gap to be filled
later. A value is set only where a scraper can say how it was established.

Written by hand rather than autogenerated, for the reason recorded in 81b8abce3858:
`init_db` calls `Base.metadata.create_all` on the healthy path, so a development
database already carries the column by the time autogenerate runs and the comparison
comes back empty.

Revision ID: c3e5a71b40f2
Revises: a4f1c2d7e8b9
Create Date: 2026-09-12 16:04:11.882301
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c3e5a71b40f2"
down_revision: Union[str, None] = "a4f1c2d7e8b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# SQLAlchemy stores an Enum column as VARCHAR with a CHECK constraint. The constraint
# is named so the downgrade can drop it on backends that keep it separately; SQLite
# rebuilds the table under batch_alter_table either way.
AVAILABILITY = sa.Enum("NOT_PUBLISHED", "NO_FIRMWARE", name="firmwareavailability")


def upgrade() -> None:
    with op.batch_alter_table("device_models") as batch:
        batch.add_column(sa.Column("firmware_availability", AVAILABILITY, nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("device_models") as batch:
        batch.drop_column("firmware_availability")
