"""Add firmware_versions.version_sort_key

The catalogue sorts every product by version and then shows one page of the result, so
the sort has to happen in SQL -- before the slice, not after it. SQLite cannot compare
the tuple `parse_version` produces, so each version's numbers are zero-padded and
stored as a string whose lexicographic order is that same comparison. The encoding
lives in src/devices/versions.py and is imported here rather than repeated, so a
backfilled row and a row written tomorrow cannot disagree.

Backfilled for every row already stored. A NULL key would sort as "this product has no
version", which is a different claim from "nobody has encoded this one yet", and the
catalogue renders those two differently.

Written by hand rather than autogenerated, for the reason recorded in 81b8abce3858:
`init_db` calls `Base.metadata.create_all` on the healthy path, so a development
database already carries the column by the time autogenerate runs and the comparison
comes back empty.

Revision ID: d7a3f9c21e84
Revises: c3e5a71b40f2
Create Date: 2026-09-16 15:12:04.118722
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.devices.versions import version_sort_key


revision: str = "d7a3f9c21e84"
down_revision: Union[str, None] = "c3e5a71b40f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


INDEX_NAME = "ix_firmware_versions_version_sort_key"


def upgrade() -> None:
    with op.batch_alter_table("firmware_versions") as batch:
        batch.add_column(sa.Column("version_sort_key", sa.String(length=255), nullable=True))

    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id, version FROM firmware_versions")).fetchall()
    for row_id, version in rows:
        bind.execute(
            sa.text("UPDATE firmware_versions SET version_sort_key = :key WHERE id = :id"),
            {"key": version_sort_key(version or ""), "id": row_id},
        )

    op.create_index(INDEX_NAME, "firmware_versions", ["version_sort_key"])


def downgrade() -> None:
    op.drop_index(INDEX_NAME, table_name="firmware_versions")
    with op.batch_alter_table("firmware_versions") as batch:
        batch.drop_column("version_sort_key")
