"""Add scrape_runs.devices_discovered

`devices_total` used to hold the length of the scraped device list while the three
absence counts beside it were taken over the vendor's stored models -- two different
populations in one row. Roland recorded total=35 next to not_checked=184 on
2026-09-15: 35 was that day's batch and 184 was counted over the 219 models in the
database, so the absences exceeded the total they sat beside. `devices_total` now
means the catalogue the run actually walked, and this column carries what the index
offered.

Nullable with no backfill, deliberately. NULL means "no claim was made", which is the
honest reading for every row written before this and for the batching scrapers, whose
lists are a fifth or a sixth of their catalogue by design and would otherwise read as
a vanished catalogue on every run. A backfill would have to invent one of those two
meanings for 774 historical rows, and the page's shrink test treats NULL as "say
nothing" precisely so history cannot flag retroactively.

Written by hand rather than autogenerated, for the reason recorded in 81b8abce3858:
`init_db` calls `Base.metadata.create_all` on the healthy path, so a development
database already carries the column by the time autogenerate runs and the comparison
comes back empty.

Revision ID: f2c8d1a94b70
Revises: d7a3f9c21e84
Create Date: 2026-09-17 18:40:11.507293
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "f2c8d1a94b70"
down_revision: Union[str, None] = "d7a3f9c21e84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("scrape_runs") as batch:
        batch.add_column(sa.Column("devices_discovered", sa.Integer(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("scrape_runs") as batch:
        batch.drop_column("devices_discovered")
